import type { User, Deal, CtaHistory, TimelineEvent, StumbleRecord, FunnelKpi, ExitMetrics, UserTag } from './types';

// ===== モックタグ =====
export const mockTags: UserTag[] = [
  { id: 'tag-1', label: '高確度', color: 'green' },
  { id: 'tag-2', label: '補助金候補', color: 'green' },
  { id: 'tag-3', label: 'フォロー必要', color: 'orange' },
  { id: 'tag-4', label: '要再アプローチ', color: 'orange' },
  { id: 'tag-5', label: 'IT苦手', color: 'gray' },
  { id: 'tag-6', label: '決裁者', color: 'green' },
  { id: 'tag-7', label: '紹介可能', color: 'green' },
  { id: 'tag-8', label: '予算あり', color: 'green' },
  { id: 'tag-9', label: '繁忙期', color: 'orange' },
  { id: 'tag-10', label: 'インボイス対応済', color: 'gray' },
];

// ===== モックユーザー =====
export const mockUsers: User[] = [
  {
    id: 'u-001',
    line_user_id: null,
    preferred_name: '田中太郎',
    company_name: '田中建設株式会社',
    industry: '建設業',
    level: 42,
    score: 87,
    recommended_exit: 'veteran_ai',
    customer_status: 'meeting',
    lead_source: 'apo',
    lead_note: '請求管理がExcelで限界。インボイス対応が急務。',
    axis_scores: { a1: 3, a2: 8, b: 12, c: 6, d: 15 },
    prev_scores: null,
    weak_axis: 'a1',
    badges: ['cta_fired', 'action_boost'],
    last_action_at: '2026-03-21T14:30:00Z',
    last_completed_step: 'S11 - 請求書テンプレート作成',
    steps_completed: 18,
    stumble_count: 3,
    stumble_how_count: 1,
    created_at: '2026-02-15T09:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-1', 'tag-2', 'tag-6'],
  },
  {
    id: 'u-002',
    line_user_id: null,
    preferred_name: '鈴木花子',
    company_name: '鈴木デザイン事務所',
    industry: 'デザイン',
    level: 28,
    score: 65,
    recommended_exit: 'taskmate',
    customer_status: 'prospect',
    lead_source: 'threads',
    lead_note: null,
    axis_scores: { a1: 10, a2: 6, b: 5, c: 8, d: 12 },
    prev_scores: null,
    weak_axis: 'b',
    badges: ['new_this_week'],
    last_action_at: '2026-03-20T10:15:00Z',
    last_completed_step: 'S06 - タスク整理',
    steps_completed: 8,
    stumble_count: 2,
    stumble_how_count: 0,
    created_at: '2026-03-17T11:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-7'],
  },
  {
    id: 'u-003',
    line_user_id: null,
    preferred_name: '山田一郎',
    company_name: '山田製作所',
    industry: '製造業',
    level: 8,
    score: 22,
    recommended_exit: 'techstars',
    customer_status: 'prospect',
    lead_source: 'apo',
    lead_note: 'うちの社員はパソコンが苦手で…紙の台帳中心。',
    axis_scores: { a1: 4, a2: 5, b: 6, c: 4, d: 3 },
    prev_scores: null,
    weak_axis: 'd',
    badges: [],
    last_action_at: '2026-03-18T16:00:00Z',
    last_completed_step: 'S02 - PC基本操作',
    steps_completed: 2,
    stumble_count: 5,
    stumble_how_count: 4,
    created_at: '2026-03-10T08:30:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-5', 'tag-3'],
  },
  {
    id: 'u-004',
    line_user_id: null,
    preferred_name: '佐藤美咲',
    company_name: '佐藤不動産',
    industry: '不動産',
    level: 55,
    score: 92,
    recommended_exit: 'custom_dev',
    customer_status: 'contacted',
    lead_source: 'apo',
    lead_note: '物件管理を一気にシステム化したい。予算は補助金で。',
    axis_scores: { a1: 12, a2: 14, b: 8, c: 10, d: 13 },
    prev_scores: null,
    weak_axis: 'b',
    badges: ['cta_fired', 'action_boost'],
    last_action_at: '2026-03-22T09:00:00Z',
    last_completed_step: 'S20 - 業務フロー可視化',
    steps_completed: 24,
    stumble_count: 1,
    stumble_how_count: 0,
    created_at: '2026-01-20T10:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-1', 'tag-8', 'tag-2'],
  },
  {
    id: 'u-005',
    line_user_id: null,
    preferred_name: '高橋健太',
    company_name: '高橋運送',
    industry: '運送業',
    level: 35,
    score: 58,
    recommended_exit: 'veteran_ai',
    customer_status: 'techstars_grad',
    lead_source: 'apo',
    lead_note: '研修後にベテランAI導入を検討中',
    axis_scores: { a1: 5, a2: 9, b: 10, c: 7, d: 14 },
    prev_scores: { a1: 3, a2: 5, b: 6, c: 4, d: 2 },
    weak_axis: 'a1',
    badges: ['techstars_grad', 'action_boost'],
    last_action_at: '2026-03-21T11:30:00Z',
    last_completed_step: 'S14 - 売上管理シート',
    steps_completed: 15,
    stumble_count: 2,
    stumble_how_count: 1,
    created_at: '2025-12-01T09:00:00Z',
    techstars_started_at: '2026-01-10T09:00:00Z',
    techstars_completed_at: '2026-03-10T09:00:00Z',
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-4', 'tag-9'],
  },
  {
    id: 'u-006',
    line_user_id: null,
    preferred_name: '伊藤裕子',
    company_name: 'イトウ会計事務所',
    industry: '会計',
    level: 20,
    score: 45,
    recommended_exit: 'veteran_ai',
    customer_status: 'prospect',
    lead_source: 'x',
    lead_note: null,
    axis_scores: { a1: 4, a2: 10, b: 11, c: 9, d: 11 },
    prev_scores: null,
    weak_axis: 'a1',
    badges: ['inactive_30d'],
    last_action_at: '2026-02-18T15:00:00Z',
    last_completed_step: 'S08 - 請求フロー確認',
    steps_completed: 6,
    stumble_count: 3,
    stumble_how_count: 2,
    created_at: '2026-02-01T10:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-3'],
  },
  {
    id: 'u-007',
    line_user_id: null,
    preferred_name: '渡辺誠',
    company_name: '渡辺飲食グループ',
    industry: '飲食',
    level: 15,
    score: 38,
    recommended_exit: 'taskmate',
    customer_status: 'prospect',
    lead_source: 'instagram',
    lead_note: null,
    axis_scores: { a1: 8, a2: 7, b: 4, c: 6, d: 13 },
    prev_scores: null,
    weak_axis: 'b',
    badges: [],
    last_action_at: '2026-03-19T13:00:00Z',
    last_completed_step: 'S05 - 業務棚卸し',
    steps_completed: 5,
    stumble_count: 1,
    stumble_how_count: 0,
    created_at: '2026-03-05T14:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-9'],
  },
  {
    id: 'u-008',
    line_user_id: null,
    preferred_name: '中村拓也',
    company_name: '中村電気工事',
    industry: '電気工事',
    level: 5,
    score: 18,
    recommended_exit: 'techstars',
    customer_status: 'techstars_active',
    lead_source: 'apo',
    lead_note: '社長本人がスマホしか使えない。社員もIT苦手。',
    axis_scores: { a1: 3, a2: 3, b: 4, c: 3, d: 2 },
    prev_scores: null,
    weak_axis: 'd',
    badges: [],
    last_action_at: '2026-03-15T09:00:00Z',
    last_completed_step: null,
    steps_completed: 1,
    stumble_count: 4,
    stumble_how_count: 3,
    created_at: '2026-03-01T09:00:00Z',
    techstars_started_at: '2026-03-15T09:00:00Z',
    techstars_completed_at: null,
    paused_until: '2026-06-15T09:00:00Z',
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-5', 'tag-3'],
  },
  {
    id: 'u-009',
    line_user_id: null,
    preferred_name: '小林真理',
    company_name: '小林美容室チェーン',
    industry: '美容',
    level: 48,
    score: 78,
    recommended_exit: 'veteran_ai',
    customer_status: 'customer',
    lead_source: 'referral',
    lead_note: '3店舗の売上管理をベテランAIで一元化。補助金申請中。',
    axis_scores: { a1: 6, a2: 12, b: 14, c: 11, d: 15 },
    prev_scores: null,
    weak_axis: 'a1',
    badges: ['cta_fired'],
    last_action_at: '2026-03-22T08:00:00Z',
    last_completed_step: 'S22 - 売上レポート自動化',
    steps_completed: 22,
    stumble_count: 1,
    stumble_how_count: 0,
    created_at: '2026-01-05T09:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-1', 'tag-6', 'tag-2', 'tag-7'],
  },
  {
    id: 'u-010',
    line_user_id: null,
    preferred_name: '加藤健一',
    company_name: '加藤物流',
    industry: '物流',
    level: 31,
    score: 52,
    recommended_exit: 'taskmate',
    customer_status: 'contacted',
    lead_source: 'apo',
    lead_note: '配車管理を効率化したいが予算感が合わなかった',
    axis_scores: { a1: 9, a2: 8, b: 5, c: 7, d: 11 },
    prev_scores: null,
    weak_axis: 'b',
    badges: [],
    last_action_at: '2026-03-20T16:30:00Z',
    last_completed_step: 'S10 - スケジュール管理',
    steps_completed: 10,
    stumble_count: 2,
    stumble_how_count: 1,
    created_at: '2026-02-20T11:00:00Z',
    techstars_started_at: null,
    techstars_completed_at: null,
    paused_until: null,
    profile_picture_url: null,
    status_message: null,
    tags: ['tag-4'],
  },
];

// ===== モック成約 =====
export const mockDeals: Deal[] = [
  {
    id: 'd-001',
    user_id: 'u-005',
    exit_type: 'techstars',
    deal_amount: 150000,
    subsidy_amount: 0,
    deal_stage: 1,
    status: 'completed',
    started_at: '2026-01-10T09:00:00Z',
    completed_at: '2026-03-10T09:00:00Z',
    note: 'TECHSTARS研修3ヶ月コース修了',
  },
  {
    id: 'd-002',
    user_id: 'u-009',
    exit_type: 'veteran_ai',
    deal_amount: 5500000,
    subsidy_amount: 4400000,
    deal_stage: 1,
    status: 'active',
    started_at: '2026-03-01T09:00:00Z',
    completed_at: null,
    note: 'インボイス枠 MAX補助550万。24ヶ月契約。',
  },
  {
    id: 'd-003',
    user_id: 'u-004',
    exit_type: 'custom_dev',
    deal_amount: 3000000,
    subsidy_amount: 2000000,
    deal_stage: 1,
    status: 'active',
    started_at: '2026-03-15T09:00:00Z',
    completed_at: null,
    note: '物件管理システム受託。通常枠補助金申請中。',
  },
  {
    id: 'd-004',
    user_id: 'u-008',
    exit_type: 'techstars',
    deal_amount: 100000,
    subsidy_amount: 0,
    deal_stage: 1,
    status: 'active',
    started_at: '2026-03-15T09:00:00Z',
    completed_at: null,
    note: 'TECHSTARS研修受講中',
  },
];

// ===== CTA履歴 =====
export const mockCtaHistory: CtaHistory[] = [
  { id: 'c-001', user_id: 'u-001', trigger: 'invoice_stumble', recommended_exit: 'veteran_ai', fired_at: '2026-03-18T10:00:00Z', result: 'clicked' },
  { id: 'c-002', user_id: 'u-004', trigger: 'action_boost', recommended_exit: 'custom_dev', fired_at: '2026-03-12T14:00:00Z', result: 'converted' },
  { id: 'c-003', user_id: 'u-009', trigger: 'subsidy_timing', recommended_exit: 'veteran_ai', fired_at: '2026-02-25T09:00:00Z', result: 'converted' },
  { id: 'c-004', user_id: 'u-003', trigger: 'it_literacy', recommended_exit: 'techstars', fired_at: '2026-03-15T11:00:00Z', result: 'pending' },
  { id: 'c-005', user_id: 'u-005', trigger: 'action_boost', recommended_exit: 'veteran_ai', fired_at: '2026-03-19T15:00:00Z', result: 'clicked' },
];

// ===== タイムライン (u-001用) =====
export const mockTimeline: TimelineEvent[] = [
  { id: 't-001', user_id: 'u-001', type: 'step_completed', description: 'S11 - 請求書テンプレート作成 完了', metadata: { step_id: 'S11' }, created_at: '2026-03-21T14:30:00Z' },
  { id: 't-002', user_id: 'u-001', type: 'stumble', description: 'S10 - インボイス設定 でつまずき（how）', metadata: { step_id: 'S10', type: 'how' }, created_at: '2026-03-20T11:00:00Z' },
  { id: 't-003', user_id: 'u-001', type: 'cta_fired', description: 'CTA発火: 請求まわり、まとめて解決できます', metadata: { trigger: 'invoice_stumble', exit: 'veteran_ai' }, created_at: '2026-03-18T10:00:00Z' },
  { id: 't-004', user_id: 'u-001', type: 'step_completed', description: 'S09 - 経費管理 完了', metadata: { step_id: 'S09' }, created_at: '2026-03-16T15:00:00Z' },
  { id: 't-005', user_id: 'u-001', type: 'step_completed', description: 'S08 - 請求フロー確認 完了', metadata: { step_id: 'S08' }, created_at: '2026-03-14T10:00:00Z' },
  { id: 't-006', user_id: 'u-001', type: 'stumble', description: 'S07 - メール連携 でつまずき（time）', metadata: { step_id: 'S07', type: 'time' }, created_at: '2026-03-12T09:00:00Z' },
  { id: 't-007', user_id: 'u-001', type: 'status_change', description: 'ステータス変更: prospect → contacted', metadata: { from: 'prospect', to: 'contacted' }, created_at: '2026-03-05T14:00:00Z' },
  { id: 't-008', user_id: 'u-001', type: 'note_added', description: '営業メモ: 次回面談3/25に設定', metadata: {}, created_at: '2026-03-04T16:00:00Z' },
];

// ===== stumble記録 (u-001用) =====
export const mockStumbles: StumbleRecord[] = [
  { id: 'st-001', user_id: 'u-001', step_id: 'S10', step_name: 'インボイス設定', stumble_type: 'how', created_at: '2026-03-20T11:00:00Z' },
  { id: 'st-002', user_id: 'u-001', step_id: 'S07', step_name: 'メール連携', stumble_type: 'time', created_at: '2026-03-12T09:00:00Z' },
  { id: 'st-003', user_id: 'u-001', step_id: 'S03', step_name: 'クラウド保存', stumble_type: 'how', created_at: '2026-02-28T10:00:00Z' },
];

// ===== ファネルKPI =====
export const mockFunnelKpi: FunnelKpi[] = [
  { week: '2/3',  inflow: 12, diagnosed: 10, step_started: 8,  cta_fired: 2, meeting: 1, converted: 0 },
  { week: '2/10', inflow: 15, diagnosed: 13, step_started: 11, cta_fired: 3, meeting: 2, converted: 1 },
  { week: '2/17', inflow: 8,  diagnosed: 7,  step_started: 6,  cta_fired: 1, meeting: 1, converted: 0 },
  { week: '2/24', inflow: 18, diagnosed: 16, step_started: 14, cta_fired: 4, meeting: 2, converted: 1 },
  { week: '3/3',  inflow: 14, diagnosed: 12, step_started: 10, cta_fired: 3, meeting: 2, converted: 1 },
  { week: '3/10', inflow: 20, diagnosed: 18, step_started: 15, cta_fired: 5, meeting: 3, converted: 2 },
  { week: '3/17', inflow: 16, diagnosed: 14, step_started: 12, cta_fired: 4, meeting: 2, converted: 1 },
  { week: '3/22', inflow: 11, diagnosed: 10, step_started: 8,  cta_fired: 3, meeting: 1, converted: 1 },
];

// ===== 出口別成約 =====
export const mockExitMetrics: ExitMetrics[] = [
  { exit_type: 'techstars',  count: 3, revenue: 450000,  subsidy_total: 0 },
  { exit_type: 'taskmate',   count: 4, revenue: 1200000, subsidy_total: 0 },
  { exit_type: 'veteran_ai', count: 2, revenue: 11000000, subsidy_total: 8800000 },
  { exit_type: 'custom_dev', count: 1, revenue: 3000000, subsidy_total: 2000000 },
];
